### ISSUE TITLE
This contains a virus! Beware!

### ISSUE THREAD

**Issue by NullUsxr** [LuaR0bloz/RoDDoS#1]
This zip file is riddled with viruses! Do not use this file, or trust this repositories owners/maintainers. I have reported this repository as well as it's owner to the Github safety team and I recommend you do too.
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/100100163/197323408-7aa6cb2d-28de-436a-8746-7b07b9542467.png">

**Comment by LuaR0bloz** [comment]
dude... its opensorce you can read the code.
